name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # her gün 00:00'da
  workflow_dispatch:       # elle çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: berkekarakanli
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#8B00FF
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#8B00FF&background=transparent

      - name: Publish to 'output' branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
